import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import Header from "@/components/Header";
import ReadingProgress from "@/components/ReadingProgress";
import CodeEnhancer from "@/components/CodeEnhancer";
import "./globals.css";

export const metadata: Metadata = {
  title: "kunsun.me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" suppressHydrationWarning>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body>
        <ThemeProvider
          attribute="class"
          enableSystem={false}
          defaultTheme="light"
        >
          <ReadingProgress />
          <Header />
          <main className="flex max-w-2xl w-full mx-auto bg-gradient px-4 sm:px-6">
            {children}
          </main>
          <CodeEnhancer />
        </ThemeProvider>
      </body>
    </html>
  );
}
